export const GET_MARKERS = 'GET_MARKERS'
export const ADD_MARKER = 'ADD_MARKER'
export const MARKERS_ERROR = 'MARKERS_ERROR'

export const GET_CENTER_POSITION = 'GET_CENTER_POSITION'
export const UPDATE_CENTER_POSITION = 'UPDATE_CENTER_POSITION'
export const USER_CENTER_ERROR = 'USER_CENTER_ERROR'
